on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          monorepo-tags: true

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - name: Use Node.js LTS 18.x
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - run: echo "Tag ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.releases_created }}

      - run: echo "Upload Url ${{ steps.release.outputs.upload_url }}
        if: ${{ steps.release.outputs.releases_created }}
    
      - run: echo "HTML Url ${{ steps.release.outputs.html_url }}
        if: ${{ steps.release.outputs.releases_created }}
      
      - run: echo "PR ${{ steps.release.outputs.pr }}
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --dry-run --workspaces
